/**********************************************************************************************************************
 * \file main.c
 * \copyright Copyright (C) Infineon Technologies AG 2024
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "cybsp.h"
#include <time.h>
#include "cy_sysint.h"
#include <stdio.h>
#include "cy_retarget_io.h"
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
/* RTC interrupt priority */
#define RTC_INTERRUPT_PRIORITY      3u

/* Size of buffer used in PrintDebugString() */
#define STRING_BUFFER_SIZE          80u

/* Delays */
#define LONG_DELAY_MS               100u      /* in ms */

/* SRAM Controller1 info */
#define SRAM_CONTROLLER1_START      ((uint32_t)0x28040000)
#define SRAM_CONTROLLER1_END        ((uint32_t)0x2807FFFF)

/* PWR_MODE Register definitions */
#define PWR_MODE_RETAINED           0x05FA0002
#define PWR_MODE_ENABLED            0x05FA0003

/* SRAM1 valid value */
#define VALID_VAL                   0xA5A5A5A5
#define _RTC_TM_YEAR_BASE           1900
/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
const cy_stc_sysint_t intrCfg =
{
    .intrSrc = srss_interrupt_backup_IRQn,
    .intrPriority = RTC_INTERRUPT_PRIORITY,
};
/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
void SetRtcAlarmDateTime(void);
void PrintDebugString(const char *str);
void HandleError(void);
static void RTC_Handler(void);
void rtc_from_pdl_time(cy_stc_rtc_config_t *pdlTime, const int year, struct tm *time);

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
/**********************************************************************************************************************
 * Function Name: main
 * Summary:
 *  This is the main function.
 * Parameters:
 *  none
 * Return:
 *  int
 **********************************************************************************************************************
 */
int main(void)
{
    cy_rslt_t result;
    uint32_t data = 0;
    uint32_t errCount = 0;

    /* Initialize the device and board peripherals */
    result = cybsp_init();
    if (result != CY_RSLT_SUCCESS)
    {
        CY_ASSERT(0);
    }

    /* Enable global interrupts */
    __enable_irq();
    /* set interrupt*/
    Cy_SysInt_Init(&intrCfg,RTC_Handler);
    Cy_SysInt_EnableSystemInt(intrCfg.intrSrc);
    IRQn_Type irqn = Cy_SysInt_GetNvicConnection(intrCfg.intrSrc);
    NVIC_SetPriority(NvicMux0_IRQn, intrCfg.intrPriority);
    NVIC_ClearPendingIRQ((IRQn_Type)intrCfg.intrSrc);
    NVIC_EnableIRQ(irqn);

    Cy_SCB_UART_Init(UART_HW, &UART_config, NULL);
    Cy_SCB_UART_Enable(UART_HW);
    cy_retarget_io_init(UART_HW);

    /* \x1b[2J\x1b[;H - ANSI ESC sequence for clear screen */
    printf("\x1b[2J\x1b[;H");
    printf("********************************************************************************\r\n");
    printf("RAM retention in DeepSleep mode example\r\n");
    printf("********************************************************************************\r\n");

    /* Initialize RTC */
    Cy_RTC_SelectClockSource(CY_SYSCLK_BAK_IN_CLKLF);
    Cy_RTC_Init(&RTCALM_config);

    /* Print the current date and time by UART */
    PrintDebugString("Current date and time.\r\n");

    Cy_RTC_ClearInterrupt(CY_RTC_INTR_ALARM1 | CY_RTC_INTR_ALARM2);
    Cy_RTC_SetInterruptMask(CY_RTC_INTR_ALARM1 | CY_RTC_INTR_CENTURY);

    /* Writing data into SRAM Controller 1 Address space */
    for (uint32_t addr = SRAM_CONTROLLER1_START; addr < SRAM_CONTROLLER1_END; addr += 4)
    {
        *(uint32_t*)addr = VALID_VAL;
    }

    for (;;)
    {
        errCount = 0;
        /* Checking SRAM Controller 1 status before setting it to Retention Mode */
        while ((CPUSS->RAM1_STATUS & CPUSS_RAM1_STATUS_WB_EMPTY_Msk) == 0)
        {
            __NOP();
        }

        /* Enabling SRAM Retention mode */
        CPUSS->RAM1_PWR_CTL = PWR_MODE_RETAINED;

        /* Set the RTC generate alarm after 10 seconds */
        SetRtcAlarmDateTime();
        Cy_SysLib_Delay(LONG_DELAY_MS);
        /* Go to deep sleep */
        Cy_SysPm_CpuEnterDeepSleep(CY_SYSPM_WAIT_FOR_INTERRUPT);
        PrintDebugString("Wakeup from DeepSleep mode\r\n");

        /* Setting SRAM in enabled mode */
        CPUSS->RAM1_PWR_CTL = PWR_MODE_ENABLED;
        Cy_SysLib_Delay(LONG_DELAY_MS);
        /* Checking if the data written before reset is retained */
        for (uint32_t addr = SRAM_CONTROLLER1_START; addr < SRAM_CONTROLLER1_END; addr += 4)
        {
            data = *(uint32_t*)addr;
            if (data != VALID_VAL){
                errCount++;
            }
        }

        /* If data is retained then errCount value will be 0 */
        if (errCount == 0)
        {
            PrintDebugString("Value Retained after wake up\r\n");
        }
        else
        {
            PrintDebugString("Value after wake up changed.\r\n");
        }
    }
}

/**********************************************************************************************************************
 * Function Name: SetRtcAlarmDateTime
 * Summary:
 *  This functions sets the RTC alarm date and time.
 * Parameters:
 *  none
 * Return:
 *  void
 **********************************************************************************************************************
 */
void SetRtcAlarmDateTime(void)
{

    /* Print the RTC alarm time by UART */
    PrintDebugString("RTC alarm will be generated after 10 seconds\r\n");

    /* Set the RTC alarm for the specified number of seconds in the future */
    cy_stc_rtc_config_t currentTime;
    cy_stc_rtc_alarm_t alarmTime;

    uint32_t savedIntrStatus = Cy_SysLib_EnterCriticalSection();
    Cy_RTC_GetDateAndTime(&currentTime);
    Cy_SysLib_ExitCriticalSection(savedIntrStatus);

    int newSec = currentTime.sec + 10;
    int overflowMin = newSec / 60;
    newSec = newSec % 60;

    /* configure alarm*/
    alarmTime.sec = newSec;
    alarmTime.secEn = CY_RTC_ALARM_ENABLE;
    alarmTime.min = currentTime.min + overflowMin;
    alarmTime.minEn = CY_RTC_ALARM_DISABLE;
    alarmTime.hour = currentTime.hour;
    alarmTime.hourEn = CY_RTC_ALARM_DISABLE;
    alarmTime.dayOfWeek = currentTime.dayOfWeek;
    alarmTime.dayOfWeekEn = CY_RTC_ALARM_DISABLE;
    alarmTime.date = currentTime.date;
    alarmTime.dateEn = CY_RTC_ALARM_DISABLE;
    alarmTime.month = currentTime.month;
    alarmTime.monthEn = CY_RTC_ALARM_DISABLE;
    alarmTime.almEn = CY_RTC_ALARM_ENABLE;

    while(Cy_RTC_SetAlarmDateAndTime(&alarmTime,CY_RTC_ALARM_1) != CY_RET_SUCCESS);

}

/**********************************************************************************************************************
 * Function Name: PrintDebugString
 * Summary:
 *  This function print out the current date time and user string.
 * Parameters:
 *  str      Point to the user print string.
 * Return:
 *  void
 **********************************************************************************************************************
 */
void PrintDebugString(const char *str)
{
    struct tm currentDateTime = {0};
    char buffer[STRING_BUFFER_SIZE];

    /* Get the current time and date from the RTC peripheral */
    cy_stc_rtc_config_t dateTime = { .hrFormat = CY_RTC_24_HOURS };
    Cy_RTC_GetDateAndTime(&dateTime);
    const int year = (int)(dateTime.year + 2000u);
    rtc_from_pdl_time(&dateTime, year, &currentDateTime);
    /* strftime() is a C library function which is used to format date and time into string.
     * It comes under the header file "time.h" which is included by HAL (See
     * http://www.cplusplus.com/reference/ctime/strftime/)
     */
    strftime(buffer, sizeof(buffer), "%X %F", &currentDateTime);

    /* Print the the current date and time and user string */
    printf("%s: %s", buffer, str);
}

/**********************************************************************************************************************
 * Function Name: HandleError
 * Summary:
 *  User defined error handling function
 * Parameters:
 *  none
 * Return:
 *  void
 **********************************************************************************************************************
 */
void HandleError(void)
{
    /* Disable all interrupts. */
    __disable_irq();

    CY_ASSERT(0);
}

/** Wrapper around the PDL RTC interrupt handler to adapt the function signature */
static void RTC_Handler(void)
{
    cy_stc_rtc_dst_t const *dstTime = 0;
    Cy_RTC_Interrupt(dstTime, false);
}
void rtc_from_pdl_time(cy_stc_rtc_config_t *pdlTime, const int year, struct tm *time)
{
   /* The number of days that precede each month of the year, not including Feb 29 */
    static const uint16_t CUMULATIVE_DAYS[] = {0, 31, 59, 90, 120, 151, 181, 212, 243, 273, 304, 334};
    time->tm_sec = (int)pdlTime->sec;
    time->tm_min = (int)pdlTime->min;
    time->tm_hour = (int)pdlTime->hour;
    time->tm_mday = (int)pdlTime->date;
    time->tm_mon = (int)(pdlTime->month - 1u);
    time->tm_year = (int)(year - _RTC_TM_YEAR_BASE);
    time->tm_wday = (int)(pdlTime->dayOfWeek - 1u);
    time->tm_yday = (int)CUMULATIVE_DAYS[time->tm_mon] + (int)pdlTime->date - 1 +
        (((int)(pdlTime->month) >= 3 && (int)(Cy_RTC_IsLeapYear((uint32_t)year) ? 1u : 0u)));
    time->tm_isdst = -1;
}
/* [] END OF FILE */
