/**********************************************************************************************************************
 * \file main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "cy_pdl.h"
#include "cyhal.h"
#include "cybsp.h"
#include "cy_retarget_io.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
/* Initial Time and Date definitions */
#define RTC_INITIAL_DATE_SEC        0u
#define RTC_INITIAL_DATE_MIN        17u
#define RTC_INITIAL_DATE_HOUR       16u
#define RTC_INITIAL_DATE_DAY        4u
#define RTC_INITIAL_DATE_MONTH      8u
#define RTC_INITIAL_DATE_YEAR       2023u

/* RTC interrupt priority */
#define RTC_INTERRUPT_PRIORITY      3u

/* Size of buffer used in PrintDebugString() */
#define STRING_BUFFER_SIZE          80u

/* Delays */
#define LONG_DELAY_MS               100u      /* in ms */

/* SRAM Controller1 info */
#define SRAM_CONTROLLER1_START      ((uint32_t)0x28080000)
#define SRAM_CONTROLLER1_END        ((uint32_t)0x280BFFFF)

/* PWR_MODE Register definitions */
#define PWR_MODE_RETAINED           0x05FA0002
#define PWR_MODE_ENABLED            0x05FA0003

/* SRAM1 valid value */
#define VALID_VAL                   0xA5A5A5A5

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
cyhal_rtc_t g_rtcObj;

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
void SetRtcAlarmDateTime(void);
void PrintDebugString(const char *str);
void HandleError(void);

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
/**********************************************************************************************************************
 * Function Name: main
 * Summary:
 *  This is the main function.
 * Parameters:
 *  none
 * Return:
 *  int
 **********************************************************************************************************************
 */
int main(void)
{
    cy_rslt_t result;
    uint32_t data = 0;
    uint32_t errCount = 0;

    /* Initialize the device and board peripherals */
    result = cybsp_init();
    if (result != CY_RSLT_SUCCESS)
    {
        CY_ASSERT(0);
    }

    /* Enable global interrupts */
    __enable_irq();

    /* Initialize retarget-io for uart logging */
    result = cy_retarget_io_init(CYBSP_DEBUG_UART_TX, CYBSP_DEBUG_UART_RX, CY_RETARGET_IO_BAUDRATE);
    if (result != CY_RSLT_SUCCESS)
    {
        HandleError();
    }

    /* \x1b[2J\x1b[;H - ANSI ESC sequence for clear screen */
    printf("\x1b[2J\x1b[;H");
    printf("********************************************************************************\r\n");
    printf("RAM retention in DeepSleep mode example\r\n");
    printf("********************************************************************************\r\n");

    /* Initialize the System Power Management */
    cyhal_syspm_init();

    /* Initialize RTC */
    result = cyhal_rtc_init(&g_rtcObj);
    if (result != CY_RSLT_SUCCESS)
    {
        HandleError();
    }

    /* Update the initialization time and date to the RTC peripheral */
    result = cyhal_rtc_write_direct(&g_rtcObj, RTC_INITIAL_DATE_SEC, RTC_INITIAL_DATE_MIN,
                                    RTC_INITIAL_DATE_HOUR, RTC_INITIAL_DATE_DAY,
                                    RTC_INITIAL_DATE_MONTH, RTC_INITIAL_DATE_YEAR);
    if (result != CY_RSLT_SUCCESS)
    {
        HandleError();
    }

    /* Print the current date and time by UART */
    PrintDebugString("Current date and time.\r\n");

    /* Enable the alarm event to trigger an interrupt */
    cyhal_rtc_enable_event(&g_rtcObj, CYHAL_RTC_ALARM, RTC_INTERRUPT_PRIORITY, true);

    /* Writing data into SRAM Controller 1 Address space */
    for (uint32_t addr = SRAM_CONTROLLER1_START; addr < SRAM_CONTROLLER1_END; addr += 4)
    {
        *(uint32_t*)addr = VALID_VAL;
    }

    for (;;)
    {
        errCount = 0;

        /* Checking SRAM Controller 1 status before setting it to Retention Mode */
        while ((CPUSS->RAM1_STATUS & CPUSS_RAM1_STATUS_WB_EMPTY_Msk) == 0)
        {
            __NOP();
        }

        /* Enabling SRAM Retention mode */
        CPUSS->RAM1_PWR_CTL = PWR_MODE_RETAINED;

        /* Set the RTC generate alarm after 10 seconds */
        SetRtcAlarmDateTime();

        /*
         * HAL manages whether the conditions of transition to DeepSleep is met,
         * in this example, especially for UART transmission is finished or not.
         * So insert some delay until tx fifo becomes empty.
         */
        cyhal_system_delay_ms(LONG_DELAY_MS);

        /* Go to deep sleep */
        result = cyhal_syspm_deepsleep();
        if (result != CY_RSLT_SUCCESS)
        {
            HandleError();
        }

        PrintDebugString("Wakeup from DeepSleep mode\r\n");

        /* Setting SRAM in enabled mode */
        CPUSS->RAM1_PWR_CTL = PWR_MODE_ENABLED;

        /* Checking if the data written before reset is retained */
        for (uint32_t addr = SRAM_CONTROLLER1_START; addr < SRAM_CONTROLLER1_END; addr += 4)
        {
            data = *(uint32_t*)addr;
            if (data != VALID_VAL)
            {
                errCount++;
            }
        }

        /* If data is retained then errCount value will be 0 */
        if (errCount == 0)
        {
            PrintDebugString("Value Retained after wake up\r\n");
        }
        else
        {
            PrintDebugString("Value after wake up changed.\r\n");
        }
    }
}

/**********************************************************************************************************************
 * Function Name: SetRtcAlarmDateTime
 * Summary:
 *  This functions sets the RTC alarm date and time.
 * Parameters:
 *  none
 * Return:
 *  void
 **********************************************************************************************************************
 */
void SetRtcAlarmDateTime(void)
{
    cy_rslt_t result;

    /* Print the RTC alarm time by UART */
    PrintDebugString("RTC alarm will be generated after 10 seconds\r\n");

    /* Set the RTC alarm for the specified number of seconds in the future */
    result = cyhal_rtc_set_alarm_by_seconds(&g_rtcObj, 10);
    if (result != CY_RSLT_SUCCESS)
    {
        HandleError();
    }
}

/**********************************************************************************************************************
 * Function Name: PrintDebugString
 * Summary:
 *  This function print out the current date time and user string.
 * Parameters:
 *  str      Point to the user print string.
 * Return:
 *  void
 **********************************************************************************************************************
 */
void PrintDebugString(const char *str)
{
    struct tm currentDateTime = {0};
    char buffer[STRING_BUFFER_SIZE];
    cy_rslt_t result;

    /* Get the current time and date from the RTC peripheral */
    result = cyhal_rtc_read(&g_rtcObj, &currentDateTime);
    if (result != CY_RSLT_SUCCESS)
    {
        HandleError();
    }

    /* strftime() is a C library function which is used to format date and time into string.
     * It comes under the header file "time.h" which is included by HAL (See
     * http://www.cplusplus.com/reference/ctime/strftime/)
     */
    strftime(buffer, sizeof(buffer), "%X %F", &currentDateTime);

    /* Print the the current date and time and user string */
    printf("%s: %s", buffer, str);
}

/**********************************************************************************************************************
 * Function Name: HandleError
 * Summary:
 *  User defined error handling function
 * Parameters:
 *  none
 * Return:
 *  void
 **********************************************************************************************************************
 */
void HandleError(void)
{
    /* Disable all interrupts. */
    __disable_irq();

    CY_ASSERT(0);
}

/* [] END OF FILE */
